### ISSUE TITLE
Linking a heading to product details title

### ISSUE THREAD

**Issue by jen-power** [jen-power/ecommerce-pattern-library#11]
@thomasjbradley

On each Product Details page, I have a section for reviews. I'd like the subheading for each page to not just say Reviews but be linked to the name of the product page you're currently on.

Right now I just have `<h3>Reviews</h3>` in the product.html before the pattern for the actual review cards. I'm not sure how I can link the name of the product (i.e. Fancy Sheet) to the h3 tag so that when you're on the Fancy Sheet Product Details page, when you scroll down it says Fancy Sheet Reviews.

**Comment by thomasjbradley** [comment]
Make a small change on this line of code by adding a placeholder:
https://github.com/jen-power/ecommerce-pattern-library/blob/master/_layouts/product.html#L6

```html
<h3>{{page.name}} Reviews</h3>
```

`.name` matches one of the keys within your `.md` files.

**Comment by jen-power** [comment]
Perfect, thank you!

My Product details page template is completed now, I only really had two elements on the page aside from the header and footer.
