### ISSUE TITLE
Marks for Product Details page

### ISSUE THREAD

**Issue by jen-power** [jen-power/ecommerce-pattern-library#12]
@thomasjbradley

My products details page is completed!

**Comment by thomasjbradley** [comment]
Did you not end up making the colours different for the products?

**Comment by jen-power** [comment]
No, I couldn't figure out how to do it. 
I understand how the different sizes worked because the only thing that changes is the text in the markdown file and the styling is the same regardless of whatever word I put in for the size; whereas with the colours it would have to be a different coloured square (using background-colour and a fixed width/height, I think) and I can't wrap my head around how I can call to the coloured squares (which would be made with CSS) within the markdown file for each product.

**Comment by jen-power** [comment]
@thomasjbradley 

Is there a way for me to link the CSS for each of those squares to the markdown files? Or do you want me to go about it another way?

**Comment by thomasjbradley** [comment]
We would have to bypass the CSS file and write CSS directly into the HTML.

So, in your Markdown, you’d do something like this:

```yml
colours:
  - "#f00"
  - "#0f0"
```

Then in your pattern for the colours you’d do this kind of thing:

```html
{% for col in page.colours %}
  <div style="background-color:{{col}}">…
{% endfor %}
```

What we’re doing is writing CSS directly into our HTML—not good practice, but useful in some situations.

**Comment by jen-power** [comment]
@thomasjbradley

I'm still confused as to how I work in that code given that each of the colours is a radio button.

I put that code into the Product Details Card where `{% pattern form/colours %}` was and it looked like this: 

<img width="1056" alt="Screen Shot 2020-03-26 at 2 26 26 PM" src="https://user-images.githubusercontent.com/43247074/77682955-15242f00-6f6e-11ea-9af9-8c38a2736df6.png">

**Comment by jen-power** [comment]
Then if I write it like this in the actual colours.html file in my Form pattern folder

```
<div class="flex-row">
  {% for col in page.colours %}
    <div style="background-color:{{col}}">
      <input name="colour" id="colour-{{forloop.index}}" type="radio">
      <label name="colour" for="colour-{{forloop.index}}" class="square push-r-1-2 hide-custom-input" title="White" aria-label="White"></label>
    </div>
  {% endfor %}
</div>
```

It looks like this

<img width="1108" alt="Screen Shot 2020-03-26 at 2 35 38 PM" src="https://user-images.githubusercontent.com/43247074/77683748-40f3e480-6f6f-11ea-8129-0855e55a1d41.png">

**Comment by thomasjbradley** [comment]
Put the colour on the label instead of the div.

**Comment by jen-power** [comment]
Hi Thomas, 

I still really don't understand how to get this to work. I've committed and pushed the code, using the Cool Sheet as my page to test this out.

Adding the `style="background-color:{{col}}"` to either the div wrapping around label or adding it to label itself yields the same results. I'm only seeing a single green box and when I hover over it, it moves and has a thick black border.

I changed the code in colours.html to match up with how my sizes.html is but I'm still confused and not sure how to troubleshoot this.

**Comment by jen-power** [comment]
I played with it more and was able to get all the colours to show up but they're one on top of the other where I want them to be side by side. I'm only able to see all the colours if I put a div around the label, otherwise I only see a single colour.

**Comment by thomasjbradley** [comment]
I’m not sure if this is the problem, but it’s worth fixing first to confirm:
https://github.com/jen-power/ecommerce-pattern-library/blob/master/_patterns/form/colours.html#L6
The closing `>` for the open `<label>` tag is missing. Go and look 1 character before the closing `</label>` tag.

**Comment by jen-power** [comment]
Oops, fixed that. Still no change though. 
I tried adding `display: inline` to the squares to try to get them side by side but it made them disappear. Inline-block didn't change anything.

I'm also noticing that the hover state works, but not the active or input checked.

**Comment by thomasjbradley** [comment]
Delete these surrounding div tags:
- https://github.com/jen-power/ecommerce-pattern-library/blob/master/_patterns/form/colours.html#L2

Then move the `<input>` inside the for-loop; right now there’s only a single input, but many labels.

**Comment by jen-power** [comment]
Great, they're inline now! 

However, the active and input checked states still aren't working properly. The hover state works though — not sure why that's the only action that works considering the hover, focus, active, etc. attributes are all targeted with the same class of `.square`

**Comment by thomasjbradley** [comment]
Try removing this surrounding `<div>` too:
https://github.com/jen-power/ecommerce-pattern-library/blob/master/_patterns/form/colours.html#L5

**Comment by jen-power** [comment]
Perfect, thank you!

Now for accessibility — is there a way for me to code in aria-labels for each colour? I'm thinking if in the <label> class I put `aria-label:"include.colour-name"` with colour-name being in the markdown file, that I wouldn't actually be able to specify which colour is which label.

**Comment by thomasjbradley** [comment]
I think you’d have to change how the data is store in the `.md` file, more like this:

```yml
colours:
  - label: "Whatever"
    colour: "#f00"
  - label: "Whatever"
    hex: "#f00"
```

Then in the loop you’d grab each piece like `col.label` & `col.hex`

**Comment by jen-power** [comment]
Where exactly "in the loop" am I targeting the label and hex codes?

I've tried all the following and none of them work properly; on the page I just see the actual code written out for each radio button instead of the coloured box:

```
<div class="flex-row">
  {% for col in page.colours %}
    <input name="colour" id="col.hex-{{forloop.index}" type="radio">
    <label style="background-color:{{col}}" name="colour" for="col.hex-{{forloop.index}}" class="square push-r-1-2 hide-custom-input" aria-label="col.label-{{forloop.index}}"></label>
  {% endfor %}
</div>
```


```
<div class="flex-row">
  {% for col in page.colours %}
    <input name="colour" id="colour-{{forloop.col.hex.index}}" type="radio">
    <label style="background-color:{{col}}" name="colour" for="colour-{{forloop.col.hex.index}}" class="square push-r-1-2 hide-custom-input" aria-label="colour-{{forloop.col.label.index}}"></label>
  {% endfor %}
</div>
```


```
<div class="flex-row">
  {% for col in page.colours %}
    <input name="colour" id="colour-col.hex-{{forloop.index}" type="radio">
    <label style="background-color:{{col}}" name="colour" for="colour-col.hex-{{forloop.index}}" class="square push-r-1-2 hide-custom-input" aria-label="colour-col.label-{{forloop.index}}"></label>
  {% endfor %}
</div>
```


```
<div class="flex-row">
  {% for col in page.colours %}
    <input name="colour" id="colour-{{forloop.col.hex}}" type="radio">
    <label style="background-color:{{col}}" name="colour" for="colour-{{forloop.col.hex}}" class="square push-r-1-2 hide-custom-input" aria-label="{{forloop.col.label}}"></label>
  {% endfor %}
</div>
```

I guess I'm just confused by what each attribute actually means in the loop code, so I can't seem to piece it together properly.

**Comment by thomasjbradley** [comment]
```
  {% for col in page.colours %}
    <input name="colour" id="colour-{{forloop.index}}" type="radio">
    <label style="background-color:{{col.hex}}" name="colour" for="colour-{{forloop.index}}" class="square push-r-1-2 hide-custom-input">{{col.label}}</label>
  {% endfor %}
```

- See in `background-color` I switched it to `col.hex`
- And inside the `<label>` I added `{{col.label}}`

**Comment by jen-power** [comment]
Thank you!

Okay, the product details page is _actually_ done now!
