### ISSUE TITLE
Favicon not showing

### ISSUE THREAD

**Issue by jen-power** [jen-power/ecommerce-pattern-library#13]
@thomasjbradley

I moved my favicon.ico file into the root of the website folder and added the link code to the head in the default.html, but I'm not seeing the favicon in my browser. Not sure what I'm missing?

**Comment by thomasjbradley** [comment]
In Chrome? Have you tried other browsers?

Chrome is stupid finicky about showing favicons.

**Comment by jen-power** [comment]
Oh, it is working now! I guess it just needed some time?
But it only shows on the home page, not the products/bedding page (in both Chrome and Firefox). Shouldn't it be on every page if I added it to the default layout?

**Comment by thomasjbradley** [comment]
Yes, but you didn’t start the `href` with a `/`:
https://github.com/jen-power/ecommerce-pattern-library/blob/master/_layouts/default.html#L7
