### ISSUE TITLE
Marks for Surprise ecommerce page 2

### ISSUE THREAD

**Issue by jen-power** [jen-power/ecommerce-pattern-library#16]
@thomasjbradley

My bulk pricing page is complete!

The only thing I would've liked to have was the Call to Action button in the banner jump down the page to the next section using an `id` tag, but the url was specified in my banner.html document (instead of having `include.url`). But it still links to an appropriate place and the jump would be the same as just scrolling a little bit down the bulk pricing page anyways. 

I also adjusted the prices in the discount table.

**Comment by thomasjbradley** [comment]
🥇
