### ISSUE TITLE
Trouble getting colour options to show within pattern library

### ISSUE THREAD

**Issue by jen-power** [jen-power/ecommerce-pattern-library#17]
@thomasjbradley

My Colour Options aren't visible in my pattern library.

I've tried using the same method that we used to get Size Buttons (within the Form section) to be visible in the pattern library — using a .yml file in a folder called _data, but it doesn't seem to be working. Do I need to use a different approach?

**Comment by thomasjbradley** [comment]
Change this line to `{% for col in include.colours %}`
https://github.com/jen-power/ecommerce-pattern-library/blob/master/_patterns/form/colours.html#L3

*And I think that won’t break anything…*

**Comment by jen-power** [comment]
Perfect, thank you!
