### ISSUE TITLE
Mark for Selector Surgeon

### ISSUE THREAD

**Issue by jen-power** [jen-power/ecommerce-pattern-library#2]
@thomasjbradley

I actually did this last week but I guess you forgot to mark it off!

<img width="1272" alt="Screen Shot 2020-03-20 at 11 37 00 AM" src="https://user-images.githubusercontent.com/43247074/77180184-f3273a00-6a9f-11ea-8ddc-1f14a813ca4d.png">

**Comment by thomasjbradley** [comment]
💯
