### ISSUE TITLE
Final grade

### ISSUE THREAD

**Issue by jen-power** [jen-power/ecommerce-pattern-library#20]
@thomasjbradley

_Rationale_
The ecommerce pattern library and website I made this term is complete and encompasses most of the components and variations needed for a full ecommerce website. The descriptions within the pattern library and complete and in-depth enough to provide another web developer with enough information to utilize the patterns on their own. While the pattern library doesn't include every possible component that may be needed for an ecommerce site, most elements are present and coded in an appropriate manner.

I found the process to be an interesting exercise and often times very challenging to the point of frustration. This is the first time in all my Web Dev classes that I feel I don't have a total grasp on the coding principles taught. The interconnectedness of multiple elements and pages is still difficult for me to wrap my mind around, and I found myself not fully understanding how some of the linking worked, even when looking at all my code that was properly linked. I would have liked to be able to spend more time learning about YAML and Markdown so that I felt more comfortable coding and confident that I could complete a similar assignment on my own in the future.

I did learn a lot though, and I hope to continuing learning more coding on my own since I know it's incredibly valuable. I am grateful that I started the graphic design program when I did so I was able to gain all this coding knowledge before the program delivery changed. I enjoyed this term assignment — it was really beneficial to my learning to work through a single website and I feel much better prepared for coding I may do in the workforce.

Thank you for all your assistance this term!

_Style & design_ **3/3**
The whole pattern library is cohesive and based on a simple colour scheme that is clean and bold. The design of the pages are simple yet effective in displaying the information as well as being visually interesting.

_Patterns_ **2.5/3**
Most of the patterns needed for an ecommerce website are present, but not all. The patterns that were omitted were mostly due to my inability to code them correctly (i.e. a functioning search bar). I believe I went beyond what was expected for some of the patterns, such as the colour and size options found in the product details card — which I wanted to act appropriately as a radio button while still being customizable.

_Explanations_ **3/3**
I believe my explanations are completed to a degree that someone else could view the pattern library and build a page, especially if they had a wireframe to build off of. I tried to include specifics about when to and not to use the patterns as well as how some of them are built (i.e. linked to markdown files).

_Accessibility_ **2.5/3**
The webpages work well under standard accessibility test. As it was created I kept in mind colour schemes that would work under colour-blindness tests, made large hit areas for buttons, gave all images alt attributes, and used proper semantics for headings and styling. Only the most basic, necessary information is shown, mostly with text, with little to no presentational elements.

_Semantics_ **3/3**
I believe I used all HTML tags appropriately and correctly.

_Responsiveness_ **3/3**
The pages are responsive and maintain a simple, clean look at all screen sizes.

_Code quality_ **2.5/3**
I wouldn't say the code is perfect since there may be some additional accessibility attributes that could have been added or a better way to code some of my patterns. But overall I think the code written is well done.

_Git & commits_ **3/3**
I committed often and for specific elements, each with a descriptive message.

**22.5/24**

**Comment by thomasjbradley** [comment]
Your website turned out amazingly. And, even though difficult, you managed to add a bunch of features (like the colours) to your website that most didn’t even consider. Thanks for taking the time & putting in the effort this term!
