### ISSUE TITLE
Marks for Homepage template

### ISSUE THREAD

**Issue by jen-power** [jen-power/ecommerce-pattern-library#4]
@thomasjbradley

I completed formatting my homepage — are you able to view it or do I have to do something for that?

For the homepage section that has Featured Products, I reused the code for the Product List page (I called it Bedding) but put a limit on the number of cards displayed. Is this proper or should I have created a new line of code specific to the homepage?

`  {% for bedding in site.products limit:3 %}
    <div class="unit [ xs-1 s-1 m-1-2 l-1-3 ] gutter">
      {% pattern cards/bedding-page-card data=bedding %}
    </div>
  {% endfor %}`

**Comment by thomasjbradley** [comment]
I can see it because we set up Netlify hosting & it looks great.

That code for the featured products is perfect.

**Comment by jen-power** [comment]
Great, thank you!
