### ISSUE TITLE
Form Field Variables

### ISSUE THREAD

**Issue by jen-power** [jen-power/ecommerce-pattern-library#5]
@thomasjbradley

For the form field code, after replacing the labels with variable code, do we make a markdown file for each field in the wireframe or is that task completed by who we give the code off to?

For example, if I have a single variable code for all text-only fields, my text-field HTML file (within the Form patterns), would look like this: 

`<div class="push-1-2">
  <label for="text">{{include.data.field-name}}</label>
  <input id="text" required aria-describedby="text-error">
  <p class="error-message milli island-1-4 push-0" id="text-error">
    <i class="icon i-16"><svg><use xlink:href="images/icons.svg#error"/></svg></i>
    <span class="icon-label">{{include.data.field-error}}</span>
  </p>
</div>`

Would I then make markdown files for each instance of a text field?
For example, I'd have one file called first-name.md and within that file it would be: 

`---
field-name: First Name
field-error: Please input your first or given name
---`

The next would be:

`---
field-name: Last Name
field-error: Please input your last or family name
---`

Do I make a folder called something like "_text-fields" within the ecommerce-pattern-library? How do I link the information in the markdown files to each individual text field for each unique form field?

**Comment by thomasjbradley** [comment]
We don’t need to make Markdown files for each field in on the page. We would be doing it all manually on the page as we insert them into grids & such.

```html
<div class="unit">
  {% pattern form/text-field field-name="Name" field-error="Please provide your name." %}
</div>
```

The Markdown files are mostly for when we want to create a whole separate page out of some information.

**Comment by jen-power** [comment]
Okay, so within the text-field.html files, wherever there is variable text I should use include.field-name rather than include.data.field-name?

**Comment by thomasjbradley** [comment]
Yep!
