### ISSUE TITLE
Pattern for product details page

### ISSUE THREAD

**Issue by jen-power** [jen-power/ecommerce-pattern-library#9]
@thomasjbradley

Since I'm assuming we're not expecting our team mates to write actual content for the Product Details page, I want to link the markdown files I made initially for the reviews on the homepage so that they show up properly formatted on the Product Details page.

Is it okay if I give this piece of code to my teammate? I'm worried that they wouldn't be able to figure it out otherwise.

https://github.com/jen-power/ecommerce-pattern-library/commit/5f6e73baa1e8111a0fd3776fab0fd63e813c330e#diff-8492e236ca20f81687b183e7ffcd429dR6-R10

**Comment by thomasjbradley** [comment]
Yeah—give them whatever you think they need to accomplish the task. (Or not if we avoid teamwork 😉)
